### ISSUE TITLE
eslint: fix gulpfile

### ISSUE THREAD

**Issue by maxkoryukov** [route4me/route4me-nodejs-sdk#27]
bitHound discovered 7 LintIssues in [gulpfile.js](https://github.com/route4me/route4me-nodejs-sdk/blob/aeac7ded89bbf531e0019d7c069c60e52a574b11/gulpfile.js). For details go to [bitHound](https://www.bithound.io/github/route4me/route4me-nodejs-sdk/blob/aeac7ded89bbf531e0019d7c069c60e52a574b11/gulpfile.js).

**Comment by novapulsar** [comment]
https://github.com/markstory/lint-review

**Comment by maxkoryukov** [comment]
fixed in 3560a5c2b97104717134723dc84e10820b91935f by ignored gulpfile.

I've already enabled `eslint` for this project on Travis CI (as a build step), addiotionally , BitHound provides code reviews.

I think, `python` dependencies will be inconvenient,  especially, for browser version (see #16)

**Comment by maxkoryukov** [comment]
Just one problem: today (29 Jan) Bithound on service.. I am waiting for BH lint for entire day...
