### ISSUE TITLE
Promisify

### ISSUE THREAD

**Issue by maxkoryukov** [route4me/route4me-nodejs-sdk#34]
Add an option `promise` for `Route4Me` constructor

* `false` - work with callbacks
* `true` - use available `Promise` lib
* any other truthy value must be used as `new Promise(function(res, rej))`

**Comment by maxkoryukov** [comment]
https://visionmedia.github.io/superagent/#promise-and-generator-support

**Comment by Olman62** [comment]
Hi Maksim,

May I put Node examples in the docs?

**Comment by maxkoryukov** [comment]
@Olman62 I think yes. All examples will be in the `examples` folder, inner folders will correspond to sections of the API doc. Each example-file will have the name of corresponding bookmark:

* example for Addresses' function _markAsDetectedAsDeparted_ (straight link  https://route4me.io/docs/#mark-as-detected-as-departed) could be found in the the repository under path `examples/Addresses/mark-as-detected-as-departed.js`

**One important note:** I will refactor and rewrite examples, because now they are not in the best shape.. I will do it within the issue #31

**Comment by maxkoryukov** [comment]
I found several `return` statements, which causes to return a callback, instead of promise (this will break `.then`-chaining)

Example: https://github.com/route4me/route4me-nodejs-sdk/blob/4c82640e8bf64137f1ae190917b315d08c331524/src/resources/optimizations.js#L81
